Lesson 5 homework - Levels 1-4
konstantins-buts/jg-java-1-online-spring-tuesday-2022 pull request #125
Opened 2022-04-24 10:34 UTC by dmitry-mak

2022-04-24 16:05 UTC, daniilsjb requested changes
Тут недоделан 8-ой таск, но в остальном шикардос. По-моему в этом занятии задания приятнее, чем в предыдущем 😅

2022-04-24 16:05 UTC, daniilsjb commented on src/main/java/students/dmitry_makarov/lesson_5/level_4/task_27/MaxOfRandomArray.java
> +                                                      //большим, что программа, сначала долго думая, прекращала работу с ошибкой
Если что, в заданиях говорится о _произвольной_ размерности, не случайной. То есть можно было выбрать размер массива самостоятельно, просто конкретный размер не имеет значения. Но так тоже можно, главное только всегда ограничивать размер, чтобы он не был слишком большим :)

2022-04-24 16:05 UTC, daniilsjb commented on src/main/java/students/dmitry_makarov/lesson_5/level_4/task_27/MaxOfRandomArray.java
> +        }
Сами случайные числа тоже желательно ограничивать, а то когда все они находятся в порядке миллионов, то понять какое действительно максимальное становится затруднительно 😅

2022-04-24 16:05 UTC, daniilsjb commented on src/main/java/students/dmitry_makarov/lesson_5/level_4/task_30/OddOfRandomArray.java
> +        }
Кстати, напомню что в циклах по массивам, в которых нас не интересует текущий номер итерации, можно использовать более краткую запись. Вот так:

```java
for (int number : numbers) {
    if (number % 2 != 0) {
        System.out.print(number + " ");
    }
}
```

2022-04-26 15:39 UTC, dmitry-mak commented on src/main/java/students/dmitry_makarov/lesson_5/level_1/task_8/ArrayLength2.java
> +}
> Тут недоделан 8-ой таск, но в остальном шикардос. По-моему в этом занятии задания приятнее, чем в предыдущем 😅

Да, так было до level 6.
Два дня на нем буксую уже.
И, кажется, все-таки придется просить помощь :-/

2022-04-27 05:59 UTC, daniilsjb commented on src/main/java/students/dmitry_makarov/lesson_5/level_1/task_8/ArrayLength2.java
> +}
Если нужна помощь с какими-то заданиями, то обращайтесь! Если что, мне в Телеграме можно писать лично 🙂

2022-04-27 06:05 UTC, daniilsjb commented on src/main/java/students/dmitry_makarov/lesson_5/level_4/task_30/OddOfRandomArray.java
> +        }
Понимаю. На самом деле этот подход гораздо проще, чем вручную писать цикл с индексом `i`. Он по сути просто означает, _"исполни этот код на каждом элементе массива"_, в то время как классический подход читается скорее как, _"на каждый индекс в пределах размерности массива, возьми соответствующий элемент и исполни на нём этот код..."_ Мне кажется первое читается лучше 😂

2022-05-04 12:32 UTC, daniilsjb requested changes
С пятым занятием всё отлично, но в шестом надо подправить пару ошибок (таски 2 и 12), и ещё в 19 немного отформатировать код. Поэтому решения разных занятий предпочтительно заливать через разные pull request-ы 😄

2022-05-04 12:32 UTC, daniilsjb commented on src/main/java/students/dmitry_makarov/lesson_5/level_5/task_31/Arrays.java
> +        return create;
Это можно сократить до одной строки:

```java
public int [] create (int length) {
    return new int[length];
}
```

2022-05-04 12:32 UTC, daniilsjb commented on src/main/java/students/dmitry_makarov/lesson_5/level_6/task_34/Arrays.java
> +            System.out.println(java.util.Arrays.toString(array));
Не уверен задумано это или нет, но здесь строчка с выводом лишняя. Задача этого метода в том, чтобы заполнить массив случайными числами, их вывод в консоль происходит в методе `print`.

2022-05-04 12:32 UTC, daniilsjb commented on src/main/java/students/dmitry_makarov/lesson_5/level_6/task_36/Arrays.java
> +        return max; // looks like wrong place for "return"
Всё правильно, `return` должен быть именно здесь. Только в конце метода мы узнаём какое значение он должен вернуть.

2022-05-04 12:32 UTC, daniilsjb commented on src/main/java/students/dmitry_makarov/lesson_6/level_1/task_2/WhileDefinition2.java
> +        i++;
Этот код, конечно, компилируется, но делает не то, что надо. Поскольку `i++` находится за пределами цикла, переменная `i` никогда не увеличится, и следовательно цикл останется бесконечным. Чтобы исправить код, нужно было не убрать фигурную скобку, а добавить :)

2022-05-04 12:32 UTC, daniilsjb commented on src/main/java/students/dmitry_makarov/lesson_6/level_1/task_6/NumberUtils.java
> +    }
Тесты есть, но код по-прежнему можно упростить в одну строчку. Подскажу: результат сравнения можно возвращать напрямую из метода. Кстати, IDEA должна тоже подсказать решение 🤔

2022-05-04 12:32 UTC, daniilsjb commented on src/main/java/students/dmitry_makarov/lesson_6/level_3/task_12/ArraysServiceTest.java
> +        if (expectedResult = result) {
Тут о-о-очень нехорошая опечатка - для сравнения мы используем оператор `==`. На это стоит обратить внимание, поскольку в Java оператор `=` возвращает присвоенное значение (то есть то, что идёт справа от знака равно). Иногда это приводит к очень неприятным багам... например, что выведет этот код?

```java
boolean someCondition = false;
if (someCondition = true) {
    System.out.println("uh-oh");
} else {
    System.out.println("everything's fine");
}
```

2022-05-04 12:32 UTC, daniilsjb commented on src/main/java/students/dmitry_makarov/lesson_6/level_4/task_18/ForInfiniteLoop.java
> +        }
По-секрету скажу, в цикле `for` каждая "часть" между точками-с-запятой опциональна, и её можно не писать. Например, если не добавить условие, то цикл сразу становится бесконечным. Вот так:

```java
for (int i = 1;; i++) {
   System.out.println("Infinite loop " + i);
}
```

Это также значит, что конструкция `for (;;)` является самым коротким способом написать бесконечный цикл :)

2022-05-04 12:32 UTC, daniilsjb commented on src/main/java/students/dmitry_makarov/lesson_6/level_4/task_19/WhileInfiniteLoopBreak2.java
> +        while (x>0){
Момент касаемо форматирования, вокруг операторов ставятся пробелы. То есть `x = 1`, `x > 0`, и т.д. Ещё, перед фигурными скобками тоже ставят пробелы: `while (x > 0) {`

2022-05-05 09:02 UTC, dmitry-mak commented on src/main/java/students/dmitry_makarov/lesson_6/level_3/task_13/ArrayService.java
> +    public int duplicatesDetector(int[] array, int numberToFind) {
понятно.
То есть, тут лучше было бы переформулировать как detectingDuplicates?

2022-05-05 09:06 UTC, dmitry-mak commented on src/main/java/students/dmitry_makarov/lesson_6/level_4/task_18/ForInfiniteLoop.java
> +        }
тут вот такой момент, немного странный и обидный, что на самом деле я про это знал. И сам прочитал, и Константин говорил, и в каком-то примере даже показывал.
Но я сначала подзабыл, а потом вот почему-то решил пойти по сложному пути. Типа большой оригинал, наверно ))

2022-05-05 09:08 UTC, dmitry-mak commented on src/main/java/students/dmitry_makarov/lesson_6/level_1/task_2/WhileDefinition2.java
> +        i++;
тут постарались два моих главных соавтора- мистер Спешка и госпожа Невнимательность.

2022-05-05 09:12 UTC, dmitry-mak commented on src/main/java/students/dmitry_makarov/lesson_5/level_6/task_34/Arrays.java
> +            System.out.println(java.util.Arrays.toString(array));
забыл стереть.
Я, пока тут еще задания не очень сложные, порой добавляю такой вывод на экран, чтобы в процессе была возможность сразу контролировать, что все работает как задумано.
А метод print там потом еще отдельно есть- который по заданию нужен.
Но 31 строка это, конечно, совершенно лишнее. Временно написал для собственного удобства и потом забыл убрать

2022-05-05 20:05 UTC, daniilsjb commented on src/main/java/students/dmitry_makarov/lesson_6/level_3/task_12/ArraysServiceTest.java
> +        if (expectedResult = result) {
Верно, `someCondition` действительно постоянно будет `true`, и код выведет `uh-oh`. На самом деле Java внутри условия для `if` блока не ожидает сравнение, а только выражение, результатом которого является какое-то `boolean` значение (то есть либо `true`, либо `false`). Поскольку выражение `someCondition = true` возвращает `true`, то блок всегда будет исполнятся. Строго говоря компилятор даже не будет в этом месте смотреть на переменную `someCondition`, самого присвоения уже достаточно для исполнения блока 🤯 В общем, лучше с этим осторожнее.

И да, я заметил, что в следующем тесте всё правильно 😎👍

2022-05-05 20:06 UTC, daniilsjb commented on src/main/java/students/dmitry_makarov/lesson_6/level_3/task_13/ArrayService.java
> +    public int duplicatesDetector(int[] array, int numberToFind) {
Тогда уже скорее `detectDuplicates`, но для этой операции больше подходит слово `count`, поскольку мы их конкретно считаем.

2022-05-05 20:07 UTC, daniilsjb commented on src/main/java/students/dmitry_makarov/lesson_6/level_4/task_18/ForInfiniteLoop.java
> +        }
Понимаю! Такое часто бывает, вроде знаешь как сделать круче, но вылетает из головы. Особенно если это что-то новое для себя :D

2022-05-23 18:22 UTC, daniilsjb approved these changes

2022-05-23 18:22 UTC, merged