Lesson 3, Level 1, Task 1
konstantins-buts/jg-java-1-online-spring-tuesday-2022 pull request #59
Opened 2022-04-08 17:26 UTC by vmaksimovs

Lesson 3, Level 1, Task 1

2022-04-08 17:36 UTC, vmaksimovs reviewed
Added task 2 - task 6

2022-04-08 18:25 UTC, daniilsjb requested changes
Сейчас стоит проявлять больше внимательности к ключевому слову `public` перед объявлением классов. IDE будет их добавлять по-умолчанию, но их нужно убирать, чтобы они не засоряли глобальный "namespace". И ещё, в названии пакета `lesson3` не хватает символа `_` 😅

2022-04-08 18:25 UTC, daniilsjb commented on src/main/java/students/viktors_maksimovs/lesson3/level_1/task_1/Robot.java
> +public class Robot {
Здесь лишнее ключевое слово `public` - этот класс будет виден в других пакетах. Нужно подправить 🔍

2022-04-08 18:25 UTC, daniilsjb commented on src/main/java/students/viktors_maksimovs/lesson3/level_1/task_1/RobotDemo.java
> +public class RobotDemo {
Здесь тоже 🔍

2022-04-10 07:21 UTC, vmaksimovs reviewed
Fixes

2022-04-10 13:54 UTC, daniilsjb approved these changes
Отлично, спасибо за поправки! 😃

2022-04-10 13:54 UTC, merged